config/routes.rb
Juvia::Application.routes.draw do
  match 'api/:action(.:format)', :to => 'api'
  root :to => 'admin/dashboard#index'
  
  devise_for :users
  
  namespace :admin do
    resources :comments do
      collection do
        get :preview
      end
      member do
        put :approve
      end
    end
    resources :sites do
      member do
        get :created
        get :test
      end
    end
    resources :users
    resources :topics
  end
  
  get 'admin/dashboard', :to => 'admin/dashboard#index', :as => :dashboard
  get 'admin/dashboard/new_admin', :to => 'admin/dashboard#new_admin'
  put 'admin/dashboard/create_admin', :to => 'admin/dashboard#create_admin'
  get 'admin/dashboard/new_site', :to => 'admin/dashboard#new_site'
  put 'admin/dashboard/create_site', :to => 'admin/dashboard#create_site'
  get 'admin/help(/:action)', :to => 'admin/help'
  
  match 'test/:action', :to => 'test' if Rails.env.test?

end

app/views/layouts/_admin_sections_bar.html.erb
<nav id="sections_bar" class="container">
  <div class="row">
    <div class="sections col_9 clearleft">
      <% if can?(:read, Site) %>
        <div class="section <%= maybe_active(:sites) %>">
          <%= link_to "Sites", admin_sites_path %>
        </div>
      <% end %>
      <% if can?(:read, Comment) %>
        <div class="section <%= maybe_active(:comments) %>">
          <% counter = Comment.accessible_by(current_ability).requiring_moderation.count %>
          <% if counter == 0 %>
            <%= link_to "Comments", admin_comments_path %>
          <% else %>
            <%= link_to "Comments (#{counter})", admin_comments_path %>
          <% end %>
        </div>
      <% end %>
      <% if can?(:list, User) %>
        <div class="section <%= maybe_active(:users) %>">
          <%= link_to "Users", admin_users_path %>
        </div>
      <% end %>
    </div>
    <div class="actions col_3 omega">
      <%= button_group do %>
        <% if can?(:create, User) %>
          <%= user_pill_button_link_to 'New user', new_admin_user_path %>
        <% end %>
        <% if can?(:create, Site) %>
          <%= add_pill_button_link_to 'New site', new_admin_site_path %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_custom.html.erb
<!doctype html>  
<!--[if lt IE 7 ]> <html lang="en-us" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en-us" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en-us" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en-us" class="no-js ie9"> <![endif]-->   
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->

<head>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" />
  <meta charset="utf-8" />

  <title><% if @title %><%= @title %> - <% end %>Juvia</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" href="/favicon.ico" />

  <!-- The Columnal Grid (1140px wide base, load first), Type and image presets, and mobile stylesheet -->
  <%= stylesheet_link_tag 'columnal' %>

  <!-- Fixes for IE -->
    <!--[if lt IE 9]>
      <%= stylesheet_link_tag 'ie' %>
    <![endif]-->

    <!-- use "fixed-984px-ie.css" or "fixed-960px-ie.css for a 984px or 960px fixed width for IE6 and 7 -->
    <!--[if lte IE 7]>
      <%= stylesheet_link_tag 'fixed-984px-ie' %>
    <![endif]-->

    <!-- Fixes for IE6, only needed if IE 6 will be supported - width must match 984px or 960px of css file used above -->
    <!-- Use .imagescale to fix IE6 issues with full-column width images (class must be added to any image wider than the column it is placed into) -->
    <!--[if lte IE 6]>
      <%= stylesheet_link_tag 'ie6-984px' %>
    <![endif]-->
  <!-- End fixes for IE -->
  
  <!-- Customizations here --> 
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  
  <!-- Page build tools - only needed while creating a site, remove when launching - Gray box colors and page debugging tools -->
  <% if Rails.env.development? %>
    <%= stylesheet_link_tag 'build' %>
  <% end %>
</head>
<body>

<header class="container">
  <div class="row">
    <div id="site_logo" class="col_5 clearleft">
      <a href="http://www.phusion.nl/" class="product_creator">Phusion</a>
      <a href="/" class="product_logo"><%= image_tag 'logo-96.png', :width => 96, :height => 61, :alt => "Logo" %></a>
      <a href="/" class="product_name">Juvia</a>
      <a href="/" class="product_desc">commenting system</a>
    </div>
    <nav class="col_7 omega">
      <% if user_signed_in? %>
        <div><%= link_to current_user.email, edit_admin_user_path(current_user) %></div>
        <div><%= link_to 'Dashboard', dashboard_path %></div>
      <% else %>
        <div><%= link_to 'Login', new_user_session_path %></div>
      <% end %>
      <div><a href="/admin/help" class="<%= maybe_active(:help) %>">Help</a></div>
      <% if user_signed_in? %>
        <div><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></div>
      <% end %>
    </nav>
  </div>
</header>

<div id="container">
  <%= yield %>
</div>

<footer class="container">
  <div class="row">
    <div class="col_12 clearleft omega">
      <a href="<%= JUVIA_GITHUB_PAGE %>">Juvia</a> is created by <a href="http://www.phusion.nl/">Phusion</a> and is open source.
      Feedback, bug reports, fork &amp; contribute at <a href="<%= JUVIA_GITHUB_PAGE %>">Github</a>.
    </div>
  </div>
</footer>

<% if Rails.env.test? %>
  <div style="display: none" id="debug">
    <div class="current_user"><%= current_user.id if current_user %></div>
  </div>
<% end %>
</body>
</html>

app/views/layouts/admin.html.erb
<%= render :layout => 'layouts/custom' do %>
  <% if user_signed_in? %>
    <%= render :partial => 'layouts/admin_sections_bar' %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col_12 clearleft omega">
        <%= yield %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%= render :layout => 'layouts/custom' do %>
  <div class="container">
    <div class="row">
      <div class="col_12 clearleft omega"><%= yield %></div>
    </div>
  </div>
<% end %>

app/views/layouts/custom.html.erb
<%= render :layout => 'layouts/custom' do %>
  <%= yield %>
<% end %>

app/views/layouts/help.html.erb
<%= render :layout => 'layouts/custom' do %>
  <% if user_signed_in? %>
    <%= render :partial => 'layouts/admin_sections_bar' %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col_12 clearleft omega help page">
        <%= yield %>
      </div>
    </div>
  </div>
<% end %>