config/routes.rb
Juvia::Application.routes.draw do
  match 'api/:action(.:format)', :to => 'api'
  root :to => 'admin/dashboard#index'
  
  devise_for :users
  
  namespace :admin do
    resources :comments do
      collection do
        get :preview
      end
      member do
        put :approve
      end
    end
    resources :sites do
      member do
        get :created
        get :test
      end
    end
    resources :users
    resources :topics
  end
  
  get 'admin/dashboard', :to => 'admin/dashboard#index', :as => :dashboard
  get 'admin/dashboard/new_admin', :to => 'admin/dashboard#new_admin'
  put 'admin/dashboard/create_admin', :to => 'admin/dashboard#create_admin'
  get 'admin/dashboard/new_site', :to => 'admin/dashboard#new_site'
  put 'admin/dashboard/create_site', :to => 'admin/dashboard#create_site'
  get 'admin/help(/:action)', :to => 'admin/help'
  
  match 'test/:action', :to => 'test' if Rails.env.test?

end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user, :inverse_of => :sites
  has_many :topics, :inverse_of => :site
  has_many :comments, :through => :topics
  
  acts_as_enum :moderation_method, [:none, :akismet, :manual]
  
  validates_presence_of :name
  validates_presence_of :key
  validates_presence_of :moderation_method
  validates_presence_of :url, :if => :moderation_method_is_akismet?
  validates_presence_of :akismet_key, :if => :moderation_method_is_akismet?

  before_validation :nullify_blank_fields
  
  attr_accessible :name, :url, :moderation_method, :akismet_key
  attr_accessible :user, :user_id, :name, :key, :url,
    :moderation_method, :akismet_key, :as => :admin
  
  default_value_for(:key) { SecureRandom.hex(20).to_i(16).to_s(36) }

  def public_topics_info
    result = []
    sql = %q{
      SELECT topics.*, COUNT(comments.id) AS comment_count FROM topics
      LEFT JOIN sites ON sites.id = topics.site_id
      LEFT JOIN comments ON comments.topic_id = topics.id
      WHERE sites.id = ?
      GROUP BY topics.id
    }
    topics = Topic.find_by_sql([sql, id])
    topics.each do |topic|
      result << {
        :id    => topic.id,
        :key   => topic.key,
        :title => topic.title,
        :url   => topic.url,
        :last_posted_at => topic.last_posted_at,
        :comment_count  => topic['comment_count']
      }
    end
    result
  end

  def last_updated_topics
    topics.order(:last_posted_at => :desc)
  end

private
  def nullify_blank_fields
    self.url = nil if url.blank?
    self.akismet_key = nil if akismet_key.blank?
  end

  def moderation_method_is_akismet?
    moderation_method == :akismet
  end
end

app/controllers/admin/sites_controller.rb
class Admin::SitesController < ApplicationController
  layout 'admin'
  
  before_filter :set_navigation_ids
  
  # GET /admin/sites
  # GET /admin/sites.json
  def index
    authorize! :read, Site
    @sites = Site.accessible_by(current_ability, :read).order('name').page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @sites }
    end
  end

  # GET /admin/sites/1
  # GET /admin/sites/1.json
  def show
    @site = Site.find(params[:id])
    authorize! :read, @site

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @site }
    end
  end

  # GET /admin/sites/new
  # GET /admin/sites/new.json
  def new
    authorize! :create, Site
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @site }
    end
  end

  # GET /admin/sites/1/edit
  def edit
    @site = Site.find(params[:id])
    authorize! :update, @site
  end

  def created
    @site = Site.find(params[:id])
    authorize! :read, @site
  end

  def test
    @site = Site.find(params[:id])
    authorize! :read, @site
  end

  # POST /admin/sites
  # POST /admin/sites.json
  def create
    authorize! :create, Site
    @site = Site.new(params[:site], :as => current_user.role)
    @site.user = current_user

    respond_to do |format|
      if @site.save
        format.html { redirect_to [:admin, @site] }
        format.json { render :json => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
        format.json { render :json => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/sites/1
  # PUT /admin/sites/1.json
  def update
    @site = Site.find(params[:id])
    authorize! :update, @site

    respond_to do |format|
      if @site.update_attributes(params[:site], :as => current_user.role)
        format.html { redirect_to [:admin, @site], :notice => 'Site was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/sites/1
  # DELETE /admin/sites/1.json
  def destroy
    @site = Site.find(params[:id])
    authorize! :destroy, @site
    @site.destroy

    respond_to do |format|
      format.html { redirect_to admin_sites_path }
      format.json { head :ok }
    end
  end

private
  def set_navigation_ids
    @navigation_ids = [:dashboard, :sites]
  end
end

app/helpers/admin/sites_helper.rb
module Admin::SitesHelper
end

app/views/admin/sites/_form.html.erb
<%= form_for([:admin, @site]) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="para">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="para">
    <%= f.label :url, 'URL (optional unless moderating with Akismet)' %><br />
    <%= f.text_field :url %>
  </div>

  <div class="para">
    <strong>How do you want to moderate new comments?</strong>
    <div class="indent">
      <label class="radio_option">
        <%= f.radio_button :moderation_method, :none %>
        Don't moderate, approve all comments automatically.
      </label>
      <br />
      <label class="radio_option">
        <%= f.radio_button :moderation_method, :akismet %>
        Check spam with <a href="http://akismet.com/">Akismet</a>, approve automatically if no spam detected.
      </label>
      <br />
      <label class="radio_option">
        <%= f.radio_button :moderation_method, :manual %>
        Manually approve all comments.
      </label>
    </div>
  </div>

  <div class="para">
    <%= f.label :akismet_key %><br />
    <%= f.text_field :akismet_key %>
  </div>

  <div class="para actions">
    <%= primary_button_submit_tag(@site.new_record? ? 'Create' : 'Update') %>
    <%= button_link_to 'Cancel', [:admin, @site] %>
  </div>
<% end %>

app/views/admin/sites/_site.html.erb
<%= div_for(site, :class => 'item container') do %>
  <div class="row">
    <div class="col_9 identity_column">
      <%= small_identity_tag(:site, site.name, [:admin, site]) %>
    </div>
    <div class="col_3 last info_column">
      <%= site.topics.count %> topics,
      <%= site.comments.count %> comments
    </div>
  </div>
<% end %>

app/views/admin/sites/created.html.erb
<% @title = "Your site has been created!" %>
<h1>Your site "<%= @site.name %>" has been registered!</h1>

<p>Paste the following snippet into your web pages to embed comments:</p>

<textarea readonly class="code" onclick="this.select()" id="embedding_code"><%= html_unsafe(
  render(:partial => 'admin/help/code.txt',
      :locals => {
          :site_key  => @site.key
      }
  ))
%></textarea>

<p>Make sure you set the <strong>container</strong> option to the CSS path of the container that you wish to embed comments in!</p>

<%= positive_button_link_to 'Roger that!', [:admin, @site] %>
<%= comment_button_link_to 'See it in action', test_admin_site_path(@site) %>
<%= button_link_to 'Teach me more about embedding', '/admin/help/embedding' %>

app/views/admin/sites/edit.html.erb
<h1>Editing site <%= @site.name %></h1>
<%= render 'form' %>

app/views/admin/sites/index.html.erb
<% if @sites.empty? %>
  <div class="sites empty">
    <p>You haven't registered any sites.</p>
    <p><%= add_button_link_to 'Create a new site', new_admin_site_path %></p>
  </div>
<% else %>
  <div class="list_with_actions">
    <% if can?(:create, Site) %>
      <div class="pre actions">
        <%= add_button_link_to 'Create a new site', new_admin_site_path %>
      </div>
    <% end %>

    <div class="sites resources list">
      <%= render :partial => 'admin/sites/site', :collection => @sites %>
    </div>

    <% if can?(:create, Site) %>
      <div class="post actions">
        <%= add_button_link_to 'Create a new site', new_admin_site_path %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/sites/new.html.erb
<h1>New site</h1>
<%= render 'form' %>

app/views/admin/sites/show.html.erb
<% @title = @site.name %>
<%= large_identity_tag :site, @site.name %>

<script type="text/javascript">
function showEmbeddingCode() {
  $('#embedding_code').css('display', 'block');
  $('#show_embedding_code').hide();
  $('#hide_embedding_code').show();
}

function hideEmbeddingCode() {
  $('#embedding_code').hide();
  $('#show_embedding_code').show();
  $('#hide_embedding_code').hide();
}
</script>

<div class="site_info box">
  <div class="container">
    <div class="row">
      <div class="col_4">
        <strong>Owner</strong><br>
        <img src="//www.gravatar.com/avatar/<%= @site.user.email_md5 %>?s=22" width="22" height="22" style="display: inline-block; margin: 0 0.25em 0 0; vertical-align: middle">
        <%= link_to @site.user.email, [:admin, @site.user] %>
      </div>
      <div class="col_4">
        <strong>Moderation method</strong><br>
        <% if @site.moderation_method == :none %>
          None
        <% elsif @site.moderation_method == :akismet %>
          Automatically with Akismet
        <% elsif @site.moderation_method == :manual %>
          Manual
        <% else %>
          <% raise "Unknown moderation method #{@site.moderation_method.inspect}" %>
        <% end %>
      </div>
      <div class="col_4 omega">
        <strong>URL</strong><br>
        <% if @site.url %>
          <%= link_to @site.url, @site.url %>
        <% else %>
          None
        <% end %>
      </div>
    </div>
    <div class="row" style="margin-top: 1em">
      <div class="col_12 omega">
        <strong>Site key</strong><br>
        <input type="text" readonly value="<%= @site.key %>" onclick="this.select()">
        <%= button_link_to 'Show embedding code',
          'javascript:void(showEmbeddingCode())',
          :id => 'show_embedding_code' %>
        <%= button_link_to 'Hide embedding code',
          'javascript:void(hideEmbeddingCode())',
          :id => 'hide_embedding_code', :style => "display: none; margin-left: 0" %>
        <%= button_link_to 'Embedding help', '/admin/help/embedding', :style => 'margin-left: 0' %>
        <textarea readonly class="code" style="margin-top: 0.5em; display: none" onclick="this.select()" id="embedding_code"><%= html_unsafe(
          render(:partial => 'admin/help/code.txt',
              :locals => {
                  :site_key  => @site.key
              }
          ))
        %></textarea>
      </div>
    </div>
    <div class="row actions" style="margin-top: 1em">
      <div class="col_12 omega">
        <strong>Actions</strong><br>
        <%= comment_button_link_to 'Test site: see how a comment page looks like', test_admin_site_path(@site) %>
        <%= edit_button_link_to 'Edit', edit_admin_site_path(@site) %>
        <%= danger_remove_button_link_to 'Delete', [:admin, @site],
          :confirm => 'Are you sure? All topics and comments for this site will also be deleted!',
          :method => :delete %>
      </div>
    </div>
  </div>
</div>

<h3>Topics</h3>
<% if @site.topics.empty? %>
  <p>This site doesn't have any topics yet.</p>
  <p>You don't have to manually create topics. A topic is automatically
  created whenever a user posts a comment with a certain topic ID.</p>
<% else %>
  <p>You don't have to manually create topics. A topic is automatically
  created whenever a user posts a comment with a certain topic ID.</p>
  
  <div class="topics resources list">
    <%= render :partial => 'admin/topics/topic', :collection => @site.last_updated_topics %>
  </div>
<% end %>

app/views/admin/sites/test.html.erb
<% @title = "Test page for site #{@site.name}" %>
<h2>Test page for site <%= link_to @site.name, [:admin, @site] %></h2>

<p>On this page you see how an embedded Juvia comments page for the site "<%= @site.name %>" looks like.
The used <code>topic_key</code> is <strong>test</strong> and the code is as follows:</p>

<textarea readonly class="code" onclick="this.select()" id="embedding_code"><%= html_unsafe(
  render(:partial => 'admin/help/code.txt',
      :locals => {
          :container => '#comments',
          :site_key  => @site.key,
          :topic_key => 'test'
      }
  ))
%></textarea>

<hr>

<div id="comments">Loading...</div>
<%= render(:partial => 'admin/help/code.txt',
      :locals => {
          :container => '#comments',
          :site_key  => @site.key,
          :topic_key => 'test'
      }
) %>